baseURL = "http://camflow.org/"
languageCode = "en-us"

title = "CamFlow"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "Learn more"
sidebarColor = "blue"
customCss = []

[[menu.shortcuts]]
name = "CamFlow on Github"
url = "https://github.com/CamFlow"
weight = 10

[[menu.shortcuts]]
name = "Create issue regarding the documentation"
url = "https://github.com/CamFlow/website/issues"
weight = 10
